config/routes.rb
TravelWebsite::Engine.routes.draw do
  #match 'home(/:action)' => 'home'
  resource :account
  resource :myaccount
  resources :telephones, :emails, :addresses
  resources :pages, :tour_orders
  #resources :tours do
  #  member do
  #    get 'order'
  #    post 'order'
  #  end
    #match 'order' => 'orders#new', :via => :get
    #match 'order' => 'orders#edit', :via => :post
    #match 'prices' => 'orders#prices'
  #end
  resources :orders do
    get 'payment', :on => :member
  end
  resources :pay_credit_cards, :user_infos
  #match 'barcode/:str' => 'barcode#gen'
end

app/controllers/travel_website/accounts_controller.rb
module TravelWebsite
class AccountsController < ApplicationController
  before_filter :authenticate_user!

  def show
    u = current_user
    unless u.user_info
      ui = u.build_user_info
      ui.full_name = u.email.split('@').first
      em = ui.emails.build
      em.email_address = u.email
      ui.save
    end
    @user_info = current_user.user_info
  end
  def update
    @user_info = current_user.user_info
    respond_with_bip @user_info
  end
end
end

app/controllers/travel_website/addresses_controller.rb
module TravelWebsite
class AddressesController < SimpleResourcesController
end
end


app/controllers/travel_website/application_controller.rb
module TravelWebsite
class ApplicationController < ActionController::Base
	before_filter :set_locale
	helper_method :title
	helper_method 'title='
	helper 'travel_website/application'

  # can be used in views as well as controllers.
  # e.g. <% title = 'This is a custom title for this view' %>
  attr_writer :title
  attr_reader :cfg

  def cfg
    AppConfig.instance
  end
  def title
  	@title ||= cfg.get_config(:site_name)
  end

	def set_locale
	  I18n.locale = extract_locale_from_tld || I18n.default_locale
	end
	def extract_locale_from_tld
    if Rails.env.development? && session[:current_local] && session[:current_local] == 'zh'
      parsed_locale = 'zh'
    else
  	  parsed_locale = request.host.split('.').first
    end
	  I18n.available_locales.include?(parsed_locale.to_sym) ? parsed_locale  : nil
	end
  def after_sign_in_path_for(resource)
    if resource.is_a?(Employee)
      log = Log.new
      log.employee_info = resource.employee_info
      log.current_sign_in_at = resource.current_sign_in_at
      log.last_sign_in_at = resource.last_sign_in_at
      log.sign_in_count = resource.sign_in_count
      log.page_url = request.headers['PATH_INFO']
      log.host = request.headers['SERVER_NAME']
      log.remote_addr = request.headers['REMOTE_ADDR']
      log.remote_host = request.headers['REMOTE_HOST']
      log.controller = controller_name
      log.action = action_name
      log.log_text = request.headers.to_s
      log.log_brief = 'view ' + log.controller + '#' + log.action 
      log.level = 2
      log.save
      cfg.get_config(:admin_path)
    else
      super
    end
  end
  
end
end

app/controllers/travel_website/destinations_controller.rb
module TravelWebsite
class DestinationsController < ApplicationController

  def index
    @destinations = Destination.where(:status => 1).includes(:description)
  end
  def show
    @destination = Destination.find(params[:id])
    tours = Spot.select('DISTINCT tour_id').where(:destination_id => @destination.id).collect{|spot| spot.tour_id}
    @related_tours = Tour.find(tours)
  end
end
end

app/controllers/travel_website/emails_controller.rb
module TravelWebsite
class EmailsController < SimpleResourcesController
end
end

app/controllers/travel_website/home_controller.rb
module TravelWebsite
class HomeController < ApplicationController
	def index
	end
  def get_signin_status
  end
  def zh
    if session[:current_local]
      session.delete :current_local
    else
      session[:current_local] = 'zh'
    end
    redirect_to :action => :index
  end

end
end

app/controllers/travel_website/myaccounts_controller.rb
module TravelWebsite
  class MyaccountsController < ApplicationController
    before_filter :authenticate_user!
    def show
      u = current_user
      unless u.user_info
        ui = u.build_user_info
        ui.full_name = u.email.split('@').first
        em = ui.emails.build
        em.email_address = u.email
        ui.save
      end
      @user_info = current_user.user_info
    end
    def update
      @user_info = current_user.user_info
      respond_with_bip @user_info
    end
  end
end


app/controllers/travel_website/orders_controller.rb
module TravelWebsite
class OrdersController < ApplicationController
  before_filter :authenticate_user!

  def new
    @tour = Tour.find(params[:tour_id])
    @order = Order.new
    @datelist = []
    @max_date = Date.today + 30
    @addresses = UserInfo.find_by_user_id(current_user.id).addresses
    if @tour.schedules.count > 0
      @datelist = @tour.schedules.map {|s| s.departure_date.strftime('%Y.%m.%d')}.join(',')
      @max_date = (@tour.schedules.last.departure_date.to_date - Date.today).to_i
    end    
  end
  def create
    @order = Order.new
    @order.schedule_id = params[:schedule_id]
    @order.order_method = 'website'
    @order.status = 0
    unless @order.save
      flash[:error] = @order.errors.full_messages.to_sentence
    else
      params[:num_adult].each do |pax|
        item = @order.order_items.build
        item.num_adult = item.num_total = pax.to_i
        item.num_child = 0
        item.save
      end
      ui = current_user.user_info
      unless ui
        ui = current_user.build_user_info
        em = ui.emails.build
        em.email_address = current_user.email
        ui.save
      end
      detail = @order.build_order_detail
      detail.user_info_id = ui.id
      detail.full_name = ui.full_name
      detail.telephone = ui.telephones.first.tel if ui.telephones.first
      detail.email = ui.emails.first.email_address if ui.emails.first
      detail.bill_address = ui.addresses.first.to_s if ui.addresses.first
      detail.save
      biz = Biz::OrderPayment.new
      biz.caculate_price(@order)
      redirect_to @order
    end
  end

  def show
    @object = Order.find(params[:id])
    raise ActionController::RoutingError.new('Not Found') unless @object.order_detail.user_info_id == current_user.user_info.id
  end
  def payment
    ui = current_user.user_info
    @object = PayCreditCard.new
    @object.full_name = ui.full_name
    order = Order.find(params[:id])
    @object.amount = order.order_price.actual_amount
    @credit_card_rate = InputType.where(:type_name => 'credit.card.rate').collect{|ipt| [ipt.type_text, ipt.type_value]}.join('|') + '|'
  end
end
end

app/controllers/travel_website/pages_controller.rb
module TravelWebsite
class PagesController < ApplicationController
  def show
    @page = Page.find_by_permalink(params[:id])
    if !@page
    	@page = Page.new
    	@page.permalink = params[:id]
    	@page.save
    end
  end
end
end

app/controllers/travel_website/passwords_controller.rb
module TravelWebsite
class PasswordsController < Devise::PasswordsController
  def create
    self.resource = resource_class.send_reset_password_instructions(resource_params)

    if successfully_sent?(resource)
      respond_with({}, :location => after_sending_reset_password_instructions_path_for(resource_name))
    else
      a_email = resource_params[:email]
      if a_email
        em = Email.where(:email_data_type => 'UserInfo').where(:email_address => a_email).first
        ui = em.email_data if em
        if ui
          if ui.user
            
          else
            u = User.new(:email => a_email)
            u.save
            ui.user = u
            ui.save
            self.resource = resource_class.send_reset_password_instructions(resource_params)
            if successfully_sent?(resource)
              respond_with({}, :location => after_sending_reset_password_instructions_path_for(resource_name))
              return
            end
          end
        end
      end
      respond_with(resource)
    end
  end
end
end

app/controllers/travel_website/pay_credit_cards_controller.rb
module TravelWebsite
class PayCreditCardsController < ApplicationController
  def create
    cc = PayCreditCard.new(params[:pay_credit_card])
    order = Order.find(params[:order_id])
    if order.status > 2
      flash[:error] = 'Cannot pay this order.'
    else
      cc.order = order
      cc.user_info = current_user.user_info
      cc.user_info.payment_tel = params[:tel]
      cc.user_info.payment_name = cc.full_name
      cc.user_info.save
      ad = cc.build_address
      ad.assign_attributes(params[:address])
      if cc.save
        if order.status == 0
          order.status = 1
          order.save
        end
      else
        flash[:error] = 'Save credit card info error:' + cc.errors.all_messages.to_sentence
      end
      redirect_to order
    end
  end
  def show
    @object = PayCreditCard.find(params[:id])
    unless current_user && @object.user_info == current_user.user_info
      raise ActionController::RoutingError.new('Not Found')
    end
  end
  def destroy
    @object = PayCreditCard.find(params[:id])
    if @object.status == 0 && current_user && @object.user_info == current_user.user_info
      @object.status = 7
      @object.save
      order = @object.order
      if order && order.status == 1
        order.status = 0
        order.save
      end
    else
      flash[:error] = 'Cannot cancel this credit card payment.'
    end
    redirect_to @object.order
  end
end
end

app/controllers/travel_website/sessions123_controller.rb
module TravelWebsite
  class Sessions123Controller < Devise::SessionsController
    respond_to :json
  end
end


app/controllers/travel_website/simple_resources_controller.rb
module TravelWebsite
class SimpleResourcesController < ApplicationController
  def new
    @object = object_name.classify.constantize.new
  end
  def update
    load_object
    @object.update_attributes(params[object_name.singularize.parameterize('_')])
    respond_with_bip @object
  end
  def destroy
    load_object
    @object.destroy
  end
  def create
    @object = object_name.classify.constantize.new(params[object_name.singularize.parameterize('_')])
    if @object.is_a? Telephone
      @object.tel_number = current_user.user_info
    elsif @object.is_a? Email
      @object.email_data = current_user.user_info
    elsif @object.is_a? Address
      @object.address_data = current_user.user_info
    end
    @object.save
  end
    def destroy
      load_object
      @object.destroy
    end

  protected
  def load_object
    @object = object_name.classify.constantize.find(params[:id])
  end
  def object_name
    controller_name #.singularize
  end
end
end

app/controllers/travel_website/telephones_controller.rb
module TravelWebsite
class TelephonesController < SimpleResourcesController
end
end

app/controllers/travel_website/tours_controller.rb
module TravelWebsite
class ToursController < ApplicationController

  def index
     @tours = Tour.where('status=1').order('days')
  end

  def show
    if (params[:id] == 'bus')
      @tours = Tour.bus_tours.order('days')
      render :index
      return
    end
    if (params[:id] == 'package')
      @tours = Tour.packages.order('days')
      render :index
      return
    end
    if (params[:id] == 'cruise')
      @tours = Tour.cruises.order('days')
      render :index
      return
    end
    @tour = Tour.find(params[:id])
    @datelist = []
    rsv_date = @tour.tour_setting.days_in_advance
    rsv_date = AppConfig.instance.get_config('max_reservation_days').to_i if rsv_date == 0
    @max_date = Date.today + rsv_date
    if @tour.schedules.count > 0
      @datelist = @tour.schedules.map {|s| s.departure_date.strftime('%Y.%m.%d')}.join(',')
      @max_date = (@tour.schedules.last.departure_date.to_date - Date.today).to_i
    end
  end

  def order
    if params[:departure_date].blank?
      flash[:error] = 'Schedule not found. Please click a departure date'
    else
      @tour = Tour.find(params[:id])
      @order = Order.new
      @schedule = @tour.schedules.where('DATE(departure_date)=?', parse_date(params[:departure_date])).first
    end
  end
  def parse_date(date_str)
    r = date_str.split('/')
    Date.new(r[2].to_i, r[0].to_i, r[1].to_i)
  end
  def xxx
    tour = Tour.find(params[:id])
    order = Order.new
    order.status = 0
    order.order_method = 'website'
    order.schedule = 0
    order.order_source = tour
    order.order_method = 'Website'
    order.state = 'draft'
    params[:num_adult].each_with_index do | n, idx |
      item = order.order_items.build(:num_adult => n, :num_child => params[:num_child][idx])
      item.num_total = item.num_adult + item.num_child
      item.amount = tour.tour_price["price#{item.num_total}"] if tour.tour_price
    end
    c = order.build_order_customer
    c.customer = current_user
    c.full_name = current_user.user_info.full_name if current_user.user_info

    p = order.build_order_price
    p.num_rooms = order.order_items.count
    p.num_adult = order.order_items.sum(:num_adult)
    p.num_child = order.order_items.sum(:num_child)
    p.num_total = order.order_items.sum(:num_total)
    p.balance_amount = p.total_amount = order.order_items.sum(:amount)

    order.save
    render :text => 'order!'
  end

end
end

app/controllers/travel_website/user_infos_controller.rb
module TravelWebsite
class UserInfosController < ApplicationController
  def show
  end
  def update
    @user_info = UserInfo.find(params[:id])
    @user_info.update_attributes(params[:user_info])
    respond_with_bip(@user_info)
  end
end
end

app/helpers/travel_website/application_helper.rb
#encoding: utf-8
module TravelWebsite
  module ApplicationHelper
    def flash_messages
      [:notice, :alert, :error].map do |msg_type|
        if flash[msg_type]
          content_tag :div, flash[msg_type], :class => "flash #{msg_type}"
        else
          ''
        end
      end.join("\n").html_safe
    end
    def cfg
      AppConfig.instance
    end
    def type_text
      TypeText.instance
    end
    def title
    end
    def add_object_js_link(name, form, method, partial, where)
      link_to_function name, %{
var new_object_id = new Date().getTime(); 
var html = $("#{generate_template(form, method, :partial => partial)}".replace(/NEW_RECORD/g, new_object_id)).hide();html.appendTo($("#{where}")).slideDown('slow')}
    end    
    def generate_html(form_builder, method, options = {})
      options[:object] ||= form_builder.object.class.reflect_on_association(method).klass.new
      options[:partial] ||= method.to_s.singularize
      options[:form_builder_local] ||= :f

      form_builder.fields_for(method, options[:object], :child_index => 'NEW_RECORD') do |f|
        render(:partial => options[:partial], :locals => { options[:form_builder_local] => f })
      end

    end
    def generate_template(form_builder, method, options = {})
      escape_javascript generate_html(form_builder, method, options)
    end
    def tour_full_name(tour)
      title = tour.description.local_title(locale)
      if tour.days == 1
        if locale == :zh
          title += '1日游'
        else
          title += ' 1Day tour'
        end
      else
        if locale == :zh
           title += "#{tour.days}天#{tour.days - 1}夜"
        else
           title += " #{tour.days} Days #{tour.days - 1} Nights"
        end
      end
      title
    end
    def credit_card_number(number)
      if number.length > 8
        [number.first(4), 'X' * (number.length - 8), number.last(4)].join('-')
      else
        number
      end
    end
    def small_link(label_text, to_url, options = {})
      icon = options[:icon]
      options.delete(:icon)
      lb = label_text
      lb = "<i class='#{icon}'></i> " + label_text if icon
      unless options[:class]
        options[:class] = 'small-link'
      end
      if options[:class] && options[:class].include?('disabled')
        options.delete(:onclick)
        options.delete(:remote)
        options.delete(:method)
        options.delete(:confirm)
        link_to(raw(lb), '#', options)
      else
        link_to( raw(lb), to_url, options)
      end
    end
  end
end

app/views/travel_website/orders/index.html.erb
<h2>My Orders</h2>

    <% current_user.user_info.orders.each do |order| %>
<table class='order-table'>
        <tr class='order-head'>
          <td colspan='4'>Order# <b><%= order.order_number %></b> Created at: <%= order.created_at %></td>
        </tr>
      <% unless order.schedule && order.order_price %>
        <td colspan='4'>Invalid order</td>
      <% else %>
        <tr>
          <td class='thumb'><%= image_tag order.schedule.tour.title_photo.pic.url(:thumb) if order.schedule.tour.title_photo %></td>
          <td class='tour-info'>
            <%= order.schedule.tour.description.title %><br />
            Departure: <%= order.schedule.departure_date %>
            Reture: <%= order.schedule.return_date %>
          </td>
          <td class='tour-price'>
            <div class='price'><%= order.order_price.actual_amount %> (<%= order.status %>)</div>
            <div class='op'>
              <%= link_to 'Detail', order_path(order) %>
              <% if order.status == 0 %>
                | <%= link_to 'Pay', payment_order_path(order) %>
              <% end %>
              <% if order.status < 2 %>
                | <%= link_to 'Cancel', order_path(order), :method => :delete %>
              <% end %>
            </div>
            <% if order.status == 1 %>
              Pay by credit card:<br />
              <% PayCreditCard.where(:order_id => order.id).where(:status => 0).each do |pcc| %>
                <%= pcc.card_type %> <%= link_to pcc.card_number, pay_credit_card_path(pcc) %><br />
              <% end %>
            <% end %>
            <div class='notes'>balance: <%= order.order_price.balance_amount %></div>
          </td>
        </tr>
      <% end %>
    </tr>
</table>
<br />
    <% end %>

app/views/travel_website/orders/index.html.haml
%h2 My Orders
- current_user.user_info.orders.each do |order|
  %table.order-table
    %tr.order-head
      %td{:colspan => "4"}
        Order#
        %b= order.order_number
        Created at: #{order.created_at}
    - unless order.schedule && order.order_price
      %td{:colspan => "4"} Invalid order
    - else
      %tr
        %td.thumb= image_tag order.schedule.tour.title_photo.pic.url(:thumb) if order.schedule.tour.title_photo
        %td.tour-info
          = order.schedule.tour.description.title
          %br/
          Departure: #{order.schedule.departure_date}
          Reture: #{order.schedule.return_date}
        %td.tour-price
          .price
            = order.order_price.actual_amount
            (#{order.status})
          .op
            = link_to 'Detail', order_path(order)
            - if order.status == 0
              | #{link_to 'Pay', payment_order_path(order)}
            - if order.status < 2
              | #{link_to 'Cancel', order_path(order), :method => :delete}
          - if order.status == 1
            Pay by credit card:
            %br/
            - PayCreditCard.where(:order_id => order.id).where(:status => 0).each do |pcc|
              = pcc.card_type
              = link_to pcc.card_number, pay_credit_card_path(pcc)
              %br/
          .notes
            balance: #{order.order_price.balance_amount}
  %br/

app/views/travel_website/orders/payment.html.erb
<% content_for :head do %>
  <%= javascript_tag do %>
    var credit_card_rate = "<%= @credit_card_rate %>";
  <% end %>
<% end %>
<%
  ui = current_user.user_info
  tel = ui.telephones.first
  default_tel = ''
  default_tel = tel.tel if tel
%>
<%= form_for( @object, :html =>{:class => 'credit-card', :onsubmit => 'return validate_cc_payment(this);'} ) do |f| %>
  <%= hidden_field_tag :order_id, params[:id] %>
  <h2>Payment details</h2>
  <ul>
    <li>
      <ul class="cards">
        <li class="visa off">Visa</li>
        <li class="mastercard off">MasterCard</li>
        <li class="amex off">Maestro</li>
      </ul>
    </li>

    <li>
      <label for="card_number">Card number</label>
      <%= f.text_field :card_number, :class => 'full-width' %>
    </li>

    <li class="vertical">
      <ul>
        <li class='expiry-date'>
          <label for="expiry_date">Expiry date <small>mm/yy</small></label>
          <%= f.text_field :valid_date, :maxlength => '5' %>
        </li>

        <li>
          <label for="cvv">CVV</label>
          <%= f.text_field :csc, :maxlength => '4'  %>
        </li>
      </ul>
    </li>
    <li>
      <label for="full_name">Name on card</label>
      <%= f.text_field :full_name, :class => 'full-width' %>
    </li>
    <li>
      <label for="tel">Tel</label>
      <%= text_field_tag :tel, default_tel, :class => 'full-width' %>
    </li>
    <li>
      <label for="address">Billing address</label>
      <%= text_field_tag 'address[address1]', '', :class => 'full-width' %>
    </li>
    <li class='vertical'>
      <ul>
        <li>
          State
          <%= text_field_tag 'address[state]', '' %>
        </li>
        <li>
          Country
          <%= text_field_tag 'address[country]', '' %>
        </li>
        <li>
          ZIP Code
          <%= text_field_tag 'address[zipcode]', '' %>
        </li>
      </ul>
    </li>

    <li class='vertical'>
      <ul>
        <li>
          Amount:
          <%= f.text_field :amount, :readonly => 'readonly' %>
        </li>
        <li>
          Service fee:
          <%= f.text_field :service_fee, :readonly => 'readonly' %>
        </li>
        <li>
          Total:
          <%= f.text_field :total_amount, :readonly => 'readonly' %>
        </li>
      </ul>
    </li>
  </ul>
  <%= f.hidden_field :card_type %>
  <p>
    <%= f.submit 'Pay by Credit Card', :id => 'pay_button', :disabled => 'disabled' %>
  </p>
<% end %>

app/views/travel_website/orders/payment.html.haml
- content_for :head do
  = javascript_tag do
    var credit_card_rate = "#{@credit_card_rate}";
- ui = current_user.user_info
- tel = ui.telephones.first
- default_tel = ''
- default_tel = tel.tel if tel
= form_for( @object, :html =>{:class => 'credit-card', :onsubmit => 'return validate_cc_payment(this);'} ) do |f|
  = hidden_field_tag :order_id, params[:id]
  %h2 Payment details
  %ul
    %li
      %ul.cards
        %li.visa.off Visa
        %li.mastercard.off MasterCard
        %li.amex.off Maestro
    %li
      %label{:for => "card_number"} Card number
      = f.text_field :card_number, :class => 'full-width'
    %li.vertical
      %ul
        %li.expiry-date
          %label{:for => "expiry_date"}
            Expiry date
            %small mm/yy
          = f.text_field :valid_date, :maxlength => '5'
        %li
          %label{:for => "cvv"} CVV
          = f.text_field :csc, :maxlength => '4'
    %li
      %label{:for => "full_name"} Name on card
      = f.text_field :full_name, :class => 'full-width'
    %li
      %label{:for => "tel"} Tel
      = text_field_tag :tel, default_tel, :class => 'full-width'
    %li
      %label{:for => "address"} Billing address
      = text_field_tag 'address[address1]', '', :class => 'full-width'
    %li.vertical
      %ul
        %li
          State
          \#{text_field_tag 'address[state]', ''}
        %li
          Country
          \#{text_field_tag 'address[country]', ''}
        %li
          ZIP Code
          \#{text_field_tag 'address[zipcode]', ''}
    %li.vertical
      %ul
        %li
          Amount:
          \#{f.text_field :amount, :readonly => 'readonly'}
        %li
          Service fee:
          \#{f.text_field :service_fee, :readonly => 'readonly'}
        %li
          Total:
          \#{f.text_field :total_amount, :readonly => 'readonly'}
  = f.hidden_field :card_type
  %p
    = f.submit 'Pay by Credit Card', :id => 'pay_button', :disabled => 'disabled'

app/views/travel_website/orders/show.html.erb
<h2>Order</h2>
<% order = @object %>
<table class='order-table order'>
        <tr class='order-head'>
          <td colspan='4'>Order# <b><%= order.order_number %></b> Created at: <%= order.created_at %></td>
        </tr>
      <% unless order.schedule && order.order_price %>
        <td colspan='4'>Invalid order</td>
      <% else %>
        <tr>
          <td class='thumb'><%= image_tag order.schedule.tour.title_photo.pic.url(:thumb) if order.schedule.tour.title_photo %></td>
          <td class='info-text'>
            <h2><%= tour_full_name(order.schedule.tour) %></h2>
            Departure: <%= label_tag order.schedule.departure_date %>
            Reture: <%= label_tag order.schedule.return_date %>
            <p>
              <table>
                <% order.order_items.each_with_index do |item, idx| %>
                  <tr>
                    <td>Room <%= idx + 1 %></td>
                    <td align='center'><%= item.num_total %>PAX</td>
                    <td align='right'>amount: <%= item.amount %></td>
                  <% end %>
                  <tr class='order-head'>
                    <td><b>Total</b></td>
                    <td align='center'><%= order.order_price.num_total %>PAX (<%= order.order_price.num_rooms %> room)</td>
                    <td align='right'><%= order.order_price.total_amount %></td>
                  </tr>
                  <tr>
                    <td colspan='2'>Additional</td>
                    <td align='right'><%= order.order_price.adjustment_amount %></td>
                  </tr>
                  <tr class='order-head'>
                    <td colspan='2'>Actual amount:</td>
                    <td align='right'><%= label_tag order.order_price.actual_amount %></td>
                  </tr>

              </table>
            </p>
          </td>
          <td class='tour-price'>
            <div class='price'><%= order.order_price.actual_amount %> (status: <%= type_text.get_text('order.status', order.status) %>)</div>
            <div class='op'>
              <% if order.status == 0 %>
                <%= link_to 'Pay', payment_order_path(order), :class => 'button orange small' %> |
              <% end %>
              <% if order.status && order.status < 2 %>
                <%= link_to 'Cancel', order_path(order), :method => :delete, :confirm => "Order incorrect? You can cancel this order before the order confirmed.\n\nAre you sure to continue ?", :class => 'button green small' %>
              <% end %>
            </div>
            <br />
            <% if order.status == 1 %>
              Pay by credit card:<br />
              <% PayCreditCard.where(:order_id => order.id).where(:status => 0).each do |pcc| %>
                <%= pcc.card_type %> <%= link_to credit_card_number(pcc.card_number), pay_credit_card_path(pcc) %><br />
              <% end %>
            <% end %>
            <div class='notes'>Balance: <%= order.order_price.balance_amount %></div>
          </td>
        </tr>
      <% end %>
    </tr>
</table>

<p>
  <%= link_to 'All orders', orders_path %>
</p>

app/views/travel_website/orders/show.html.haml
%h2 Order
- order = @object
%table.order-table.order
  %tr.order-head
    %td{:colspan => "4"}
      Order#
      %b= order.order_number
      Created at: #{order.created_at}
  - unless order.schedule && order.order_price
    %td{:colspan => "4"} Invalid order
  - else
    %tr
      %td.thumb= image_tag order.schedule.tour.title_photo.pic.url(:thumb) if order.schedule.tour.title_photo
      %td.info-text
        %h2= tour_full_name(order.schedule.tour)
        Departure: #{label_tag order.schedule.departure_date}
        Reture: #{label_tag order.schedule.return_date}
        %p
          %table
            - order.order_items.each_with_index do |item, idx|
              %tr
                %td
                  Room #{idx + 1}
                %td{:align => "center"}
                  = item.num_total
                  PAX
                %td{:align => "right"}
                  amount: #{item.amount}
            %tr.order-head
              %td
                %b Total
              %td{:align => "center"}
                = order.order_price.num_total
                PAX (#{order.order_price.num_rooms} room)
              %td{:align => "right"}= order.order_price.total_amount
            %tr
              %td{:colspan => "2"} Additional
              %td{:align => "right"}= order.order_price.adjustment_amount
            %tr.order-head
              %td{:colspan => "2"} Actual amount:
              %td{:align => "right"}= label_tag order.order_price.actual_amount
      %td.tour-price
        .price
          = order.order_price.actual_amount
          (status: #{type_text.get_text('order.status', order.status)})
        .op
          - if order.status == 0
            = link_to 'Pay', payment_order_path(order), :class => 'button orange small'
            |
          - if order.status && order.status < 2
            = link_to 'Cancel', order_path(order), :method => :delete, :confirm => "Order incorrect? You can cancel this order before the order confirmed.\n\nAre you sure to continue ?", :class => 'button green small'
        %br/
        - if order.status == 1
          Pay by credit card:
          %br/
          - PayCreditCard.where(:order_id => order.id).where(:status => 0).each do |pcc|
            = pcc.card_type
            = link_to credit_card_number(pcc.card_number), pay_credit_card_path(pcc)
            %br/
        .notes
          Balance: #{order.order_price.balance_amount}
%p
  = link_to 'All orders', orders_path